version: '3'

dotenv: ['./.env']

vars:
  IMAGE_REPO: "{{.USER}}/so-k3k"
  VERSION: 0.0.1

includes:
  dev:
    taskfile: ./setup
    dir: ./setup

tasks:
  docker-build:
    cmds:
      - docker build . -t {{.IMAGE_REPO}}:{{.VERSION}}
  docker-push:
    cmds:
      - echo $PASSWORD | docker login -u {{.USER}} --password-stdin
      - docker push {{.IMAGE_REPO}}:{{.VERSION}}
