apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "so-k3k.fullname" . }}-role
  labels:
    {{- include "so-k3k.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "so-k3k.fullname" . }}-binding
  labels:
    {{- include "so-k3k.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "so-k3k.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "so-k3k.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "so-k3k.fullname" . }}-clusterrole
  labels:
    {{- include "so-k3k.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  - persistentvolumes
  verbs: ["list", "get"]
- apiGroups: ["storage.k8s.io"]
  resources:
  - storageclasses
  verbs: ["list", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "so-k3k.fullname" . }}-clusterrolebinding
  labels:
    {{- include "so-k3k.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "so-k3k.fullname" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "so-k3k.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
