apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "so-k3k.serviceAccountName" . }}
  labels:
    {{- include "so-k3k.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
